[theme]
base = "light"
primaryColor = "#2B59C3"
backgroundColor = "#F4F5F7"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1F2430"
font = "sans serif"

[client]
showErrorDetails = true

[browser]
gatherUsageStats = false
